name: Fireflink Trigger

on:
  workflow_dispatch:

jobs:
  run-curl:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Fireflink API
        run: |
          curl --location 'https://app.v3.fireflink.com/dashboardexecution/optimize/v3/public/cicd/default-machine' \
          --header "Content-Type: application/json" \
          --header "version: phase_1" \
          --data-raw '{
            "suiteId": "SUITE_d43b62fd-d1b1-437d-9bfe-0b41e148dfb7",
            "waitConfig": {
              "captureScreenshots": "failedSteps",
              "captureVideos": "notCapture",
              "delayBetweenSteps": "2",
              "delayBetweenStepsUnit": "Seconds",
              "explicitWait": "20",
              "explicitWaitUnit": "Seconds",
              "implicitWait": "20",
              "implicitWaitUnit": "Seconds",
              "terminateScriptIfTakesMoreTime": "6",
              "terminateScriptUnit": "Minutes",
              "terminateSuiteIfTakesMoreTime": "1",
              "terminateSuiteUnit": "Hours"
            },
            "licenseId": "LIC26219",
            "accessToken": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJNTnNvS1VYQkxLS3BPblpWUUxaZWhwcGhobHdJSldCYUF4dDRkaXMwNlcwIn0.eyJleHAiOjE3NzcwMjkyODMsImlhdCI6MTc3Njk0Mjg4MywianRpIjoib25ydG5hOjViNTMzYWI5LWNkYjAtNDM1ZS04ODVlLWQ3Mjg0NGMzMTZlMSIsImlzcyI6Imh0dHBzOi8vYXBwLnYzLmZpcmVmbGluay5jb206MzAxMDEvcmVhbG1zL0ZpcmVGbGluayIsInN1YiI6ImY6ODg5MjliMDAtNzNiOC00NzRmLWJiYmMtZGIyZTFhM2UwNzk4OnRlamFzaHdpbmlAZmlyZWZsaW5rLmNvbSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRhcmdldC1jbGllbnQiLCJzaWQiOiI3ODM3MDI1NS02OTE3LTRjNmYtODdhMS1jZjU2NjBlZjlhZjgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpb["*"],"realm_access":{"roles":["offline_access","uma_authorization"]},"scope":"profile email","currentLicenseId":"LIC26219","email_verified":false,"currentPrivilege":"Admin","fullName":"Tejashwini","activationStatus":"ACTIVE","privilege":"Admin","licenseName":"fire-flink-LIC26219","preferred_username":"Tejashwini","userName":"tejashwini@fireflink.com","billingCycle":"HalfYearly","id":"USR10149034","licenseId":"LIC26219","email":"tejashwini@fireflink.com"}.kt-hkNk9kEugcBMV22rc_s_lZwnjK-ClQyuhGVlwJ2uVIpi4qqp4txRq2LFkafwOibqkSsRMJiz4ltPwsr5CyvrqWUNhlplNybQzHtylQnvfHrIwmiaUkcTXEek4cWr1u8YfiuqT524m-kSR9hSlw1V4SkA0iGxcAigIhXdbKfZGThb6Aetgr4RP9yhvg2tTock8SRwwol-mzNJQgeuH9PLiR-AVcuP2P1_wxEWYdj-sB5hwF5edIiSUxysA5JaaiEAUOVY0xRW9VmFJd0q94I2Fel9sUYZK9u0LKLHCN-JmLtKcYc2aBJHUEYDB8COfs2vfJ0qRt1oGMQGLhaooBQ",
            "projectId": "PJT1485"
          }'
